[package]
name = "cm-market-data"
edition.workspace = true
version.workspace = true

[dependencies]
cm-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
