apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-record-bybit-config
  namespace: cm
  labels:
    app: cm-record
    exchange: bybit
data:
  RECORD_EXCHANGE: "bybit"
  RECORD_SYMBOLS: "BTCUSDT,ETHUSDT,SOLUSDT,XRPUSDT,DOGEUSDT"
  RECORD_DURATION: "70m"
  S3_BUCKET: "cm-hft"
  S3_PREFIX: "recordings/bybit"
  S3_ENDPOINT: "https://s3.eu-west-1.amazonaws.com"
