[package]
name = "cm-recorder"
edition.workspace = true
version.workspace = true

[dependencies]
cm-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
